[package]
name = "sp-consensus-sassafras"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Sassafras consensus"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-std = { version = "2.0.0-alpha.5", path = "../../std", default-features = false }
sp-core = { version = "2.0.0-alpha.5", path = "../../core", default-features = false }
sp-api = { version = "2.0.0-alpha.5", default-features = false, path = "../../api" }
sp-consensus = { version = "0.8.0-alpha.5", optional = true, path = "../common" }
sp-consensus-vrf = { version = "0.8.0-alpha.5", path = "../vrf", default-features = false }
sp-inherents = { version = "2.0.0-alpha.5", path = "../../inherents", default-features = false }
sp-timestamp = { version = "2.0.0-alpha.5", path = "../../timestamp", default-features = false }
sp-runtime = { version = "2.0.0-alpha.5", path = "../../runtime", default-features = false }
sp-application-crypto = { version = "2.0.0-alpha.5", path = "../../application-crypto", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-std/std",
	"sp-core/std",
	"sp-api/std",
	"sp-consensus",
	"sp-consensus-vrf/std",
	"sp-inherents/std",
	"sp-timestamp/std",
	"sp-runtime/std",
	"sp-application-crypto/std",
]
