[package]
name = "sc-tracing"
version = "2.0.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Instrumentation implementation for substrate."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term = "0.12.1"
tracing-log = "0.1.1"
lazy_static = "1.4.0"
log = { version = "0.4.8" }
once_cell = "1.4.1"
parking_lot = "0.10.0"
regex = "1.4.2"
erased-serde = "0.3.9"
rustc-hash = "1.1.0"
serde = "1.0.101"
serde_json = "1.0.41"
slog = { version = "2.5.2", features = ["nested-values"] }
tracing = "0.1.22"
tracing-core = "0.1.17"
tracing-subscriber = "0.2.15"
sp-tracing = { version = "2.0.0", path = "../../primitives/tracing" }
sp-block-builder = { version = "2.0.0", path = "../../primitives/block-builder" }
sp-storage = { version = "2.0.0", path = "../../primitives/storage" }
sp-runtime = { version = "2.0.0", path = "../../primitives/runtime" }
sp-blockchain = { version = "2.0.0", path = "../../primitives/blockchain" }
sp-api = { version = "2.0.0", path = "../../primitives/api" }
sc-telemetry = { version = "2.0.0", path = "../telemetry" }
sc-client-api = { version = "2.0.0", path = "../api" }
