[package]
name = "manual-seal-node"
version = "2.0.0-alpha.5"
authors = ["Anonymous"]
edition = "2018"
license = "Unlicense"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[[bin]]
name = "manual-seal-node"

[dependencies]
futures = "0.3.1"
log = "0.4.8"
structopt = "0.3.8"


sc-cli = { version = "0.8.0-alpha.5", path = "../../../client/cli" }
sp-core = { version = "2.0.0-alpha.5", path = "../../../primitives/core" }
sc-executor = { version = "0.8.0-alpha.5", path = "../../../client/executor" }
sc-service = { version = "0.8.0-alpha.5", path = "../../../client/service" }
sp-inherents = { version = "2.0.0-alpha.5", path = "../../../primitives/inherents" }
sp-timestamp = { version = "2.0.0-alpha.5", path = "../../../primitives/timestamp" }
sc-transaction-pool = { version = "2.0.0-alpha.5", path = "../../../client/transaction-pool" }
sp-transaction-pool = { version = "2.0.0-alpha.5", path = "../../../primitives/transaction-pool" }
sc-network = { version = "0.8.0-alpha.5", path = "../../../client/network" }
sp-consensus = { version = "0.8.0-alpha.5", path = "../../../primitives/consensus/common" }
sc-client = { version = "0.8.0-alpha.5", path = "../../../client/" }
sc-client-api = { version = "2.0.0-alpha.5", path = "../../../client/api" }
sp-runtime = { version = "2.0.0-alpha.5", path = "../../../primitives/runtime" }
sc-basic-authorship = { path = "../../../client/basic-authorship", version = "0.8.0-alpha.5"}
sc-consensus-manual-seal = { version = "0.8.0-alpha.5", path = "../../../client/consensus/manual-seal" }
node-template-runtime = { version = "2.0.0-alpha.5", path = "../runtime", features = ["no-babe"] }

[build-dependencies]
vergen = "3.0.4"
build-script-utils = { version = "2.0.0-alpha.5", package = "substrate-build-script-utils", path = "../../../utils/build-script-utils" }
