[package]
name = "dry-run-runtime-upgrade-api"
version = "0.1.0"
authors = ["kianenigma <kian.peymani@gmail.com>"]
edition = "2018"

[dependencies]
sp-api = { version = "2.0.1", path = "../../../../primitives/api", default-features = false }

[features]
default = [ "std" ]
std = [
	"sp-api/std",
]
