# .gitlab-ci.yml
#
# substrate
#




stages:
  - test

variables:
  GIT_DEPTH: 1



deploy-chaos-example:
  stage:                           test
  image:                           parity/kubetools:latest
  only:
    - /^[0-9]+$/                   # PRs
  tags:
    # this is the runner that is used to run this job
    - kubernetes-parity-build
  environment:
    name:                          parity-chaosnet
  script:
    - echo "# substrate ci namespace ${KUBE_NAMESPACE}"
    - kubectl get pod
    - kubectl apply -f .maintain/kubernetes/kuard.yml
    - kubectl rollout status deployment/kuard-deployment
    - kubectl get all
    - kubectl get pods -o wide --sort-by="{.spec.nodeName}"
    - kubectl port-forward svc/kuard-service 8080:80 &
    - sleep 5
    - curl -sS localhost:8080
    - kill %1
    - echo "waiting for 10 min before shutting down"
    - sleep 600
    - kubectl delete -f .maintain/kubernetes/kuard.yml


