# .gitlab-ci.yml
#
# substrate
#




stages:
  - test




deploy-chaos-example:
  stage:                           test
  when:                            manual
  image:                           parity/kubetools:latest
  only:
    - /^[0-9]+$/                   # PRs
  tags:
    # this is the runner that is used to run this job
    - kubernetes-parity-build
  environment:
    name:                          parity-chaosnet
  script:
    - kubectl cluster-info


