[package]
name = "remote-test"
version = "0.1.0"
authors = ["kianenigma <kian.peymani@gmail.com>"]
edition = "2018"

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
remote-externalities = { path = "../../../../substrate-debug-kit/remote-externalities" }
logging_timer = "1.0.0"
log = "0.4.11"
env_logger = "0.7.1"
hex-literal = "0.2.1"

sp-runtime = { path = "../../../primitives/runtime" }
sp-core = { path = "../../../primitives/core" }
sp-npos-elections = { path = "../../../primitives/npos-elections" }

frame-support = { path = "../../support" }
frame-system = { path = "../../system" }
pallet-staking = { path = ".." }
pallet-staking-reward-curve = { path = "../reward-curve" }
pallet-balances = { path = "../../balances" }
pallet-session = { path = "../../session" }
pallet-timestamp = { path = "../../timestamp" }
