[package]
name = "frame-election-providers"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME election providers"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
static_assertions = "1.1.0"
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-io ={ version = "2.0.0-rc6", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "2.0.0-rc6", default-features = false, path = "../../primitives/runtime" }
sp-staking = { version = "2.0.0-rc6", default-features = false, path = "../../primitives/staking" }
frame-support = { version = "2.0.0-rc6", default-features = false, path = "../support" }
frame-system = { version = "2.0.0-rc6", default-features = false, path = "../system" }

sp-npos-elections = { version = "2.0.0-rc6", default-features = false, path = "../../primitives/npos-elections" }
sp-std = { version = "2.0.0-rc6", default-features = false, path = "../../primitives/std" }
sp-arithmetic = { version = "2.0.0-rc6", default-features = false, path = "../../primitives/arithmetic" }
sp-election-providers = { version = "2.0.0-rc6", default-features = false, path = "../../primitives/election-providers" }

# Optional imports for benchmarking
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }
rand = { version = "0.7.3", optional = true }

[dev-dependencies]
sp-io = { version = "2.0.0", path = "../../primitives/io" }
hex-literal = "0.3.1"
pallet-balances = { version = "2.0.0", path = "../balances" }
sp-core = { version = "2.0.0", path = "../../primitives/core" }
paste = "1.0.1"
substrate-test-utils = { version = "2.0.0", path = "../../test-utils" }
parking_lot = "0.10.2"
sp-tracing = { version = "2.0.0", path = "../../primitives/tracing" }

frame-benchmarking = { version = "2.0.0", path = "../benchmarking" }
rand_chacha = { version = "0.2" }
rand = "0.7.3"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-npos-elections/std",
	"frame-system/std",
	"sp-std/std",
	"sp-election-providers/std"
]
runtime-benchmarks = [
	"frame-benchmarking",
	"rand_chacha",
	"rand",
]
