[package]
name = "runtime-upgrade-dryrun-cli"
version = "2.0.0"
authors = ["kianenigma <kian.peymani@gmail.com>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-service = { version = "0.8.0", default-features = false, path = "../../../../client/service" }
sc-cli = { version = "0.8.0", path = "../../../../client/cli" }
structopt = "0.3.8"
sp-state-machine = { version = "0.8.1", path = "../../../../primitives/state-machine" }
sp-api = { version = "2.0.1", path = "../../../../primitives/api" }
sp-blockchain = { version = "2.0.1", path = "../../../../primitives/blockchain" }
sp-runtime = { version = "2.0.1", path = "../../../../primitives/runtime" }

runtime-upgrade-dryrun-api = { path = "../api" }
remote-externalities = { path = "../remote-externalities" }
