[package]
name = "pallet-session-common"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME sessions common pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-runtime = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime" }
frame-support = { version = "2.0.0", default-features = false, path = "../../support" }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"frame-support/std",
]