[package]
name = "pallet-balances-e2e-tests"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
publish = false

[dependencies]
sp-keyring = { version = "3.0.0", path = "../../../primitives/keyring" }
test-runner = { path = "../../../test-utils/test-runner", version = "0.9.0" }
num-traits = { version = "0.2.14" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../../primitives/runtime" }
frame-support = { version = "3.0.0", default-features = false, path = "../../../frame/support" }
frame-system = { version = "3.0.0", default-features = false, path = "../../../frame/system" }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
pallet-balances = { version = "3.0.0", path = "../../../frame/balances" }
