[package]
name = "remote-signer"
version = "0.1.0"
authors = ["Benjamin Kampmann <ben@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-derive = "14.2.1"
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.0"
sp-core = { version = "2.0.0-rc5", path="../../../primitives/core" }
sc-keystore = { version = "2.0.0-rc5", path="../../../client/keystore" }
futures = { version = "0.3.1", features = ["compat"] }
parking_lot = "0.11"