[package]
name = "remote-externalities"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "An externalities provided environemnt that can load itself from remote nodes or cache files"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee-http-client = { git = "https://github.com/paritytech/jsonrpsee" }
jsonrpsee-types = { git = "https://github.com/paritytech/jsonrpsee" }
# TODO: these are not supported by `jsonrpsee`
# sc-rpc-api = { path = "../../../../client/rpc-api" }
# sc-rpc = { path = "../../../../client/rpc" }

hex-literal = "0.3.1"
env_logger = "0.8.2"
log = "0.4.11"
bincode = "1.3.1"

sp-io = { path = "../../../../primitives/io" }
sp-core = { path = "../../../../primitives/core" }

[dev-dependencies]
async-std = { version = "1.6.5", features = ["attributes"] }

[features]
remote-test = []
