[package]
name = "sp-tracing"
version = "2.0.0-dev"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Instrumentation primitives and macros for Substrate."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tracing = { version = "0.1.13", optional = true }
parking_lot = { version = "0.10.0", optional = true }
lazy_static = { version = "1.4.0", optional = true }
rental = { version = "0.5.5", optional = true }
log = { version = "0.4.8", optional = true }
rustc-hash = { version = "1.1.0", optional = true }

[features]
default = [ "std" ]
std = [ "tracing", "parking_lot", "lazy_static", "rental", "log", "rustc-hash"]
