[package]
name = "sassafras-template"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"
license = "Unlicense"
build = "build.rs"

[[bin]]
name = "sassafras-template"

[dependencies]
futures = "0.3.1"
log = "0.4.8"
structopt = "0.3.8"

sc-cli = { path = "../../../client/cli" }
sp-core = { path = "../../../primitives/core" }
sc-executor = { path = "../../../client/executor" }
sc-service = { path = "../../../client/service" }
sp-inherents = { path = "../../../primitives/inherents" }
sc-transaction-pool = { path = "../../../client/transaction-pool" }
sp-transaction-pool = { path = "../../../primitives/transaction-pool" }
sc-network = { path = "../../../client/network" }
sc-consensus-sassafras = { path = "../../../client/consensus/sassafras" }
sp-consensus-sassafras = { path = "../../../primitives/consensus/sassafras" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sc-client = { path = "../../../client/" }
sc-client-api = { version = "2.0.0-alpha.5", path = "../../../client/api" }
sp-runtime = { path = "../../../primitives/runtime" }
sc-basic-authorship = { path = "../../../client/basic-authorship" }
grandpa = { package = "sc-finality-grandpa", path = "../../../client/finality-grandpa" }
grandpa-primitives = { package = "sp-finality-grandpa", path = "../../../primitives/finality-grandpa" }
sassafras-template-runtime = { path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0-alpha.5", path = "../../../utils/build-script-utils" }
